### ISSUE TITLE
Consulta por un libro de referencia

### ISSUE THREAD

**Issue by victorchoke** [Caneda/Docs#1]
Hola tendrás algún libro o texto que recomiendes para empezar a realizar simulaciones.
Mas que nada que explique los tipos de simulaciones, la configuración de parámetros, etc. Como se presenta la información en los gráficos.

**Comment by victorchoke** [comment]
Osea conozco el ngspice-manual, pero no se si tendrás un material mejor, o mas pedagógico con ejemplos y ejercicios.

**Comment by parejaobregon** [comment]
Hola Victor,

Lamentablemente no tengo a mano ninguna bibliografía para recomendar en cuanto a la simulación y los detalles que me preguntás. En ese sentido, mi idea es ir agregando documentación en [1] a medida que pueda, aunque por una cuestión de tiempo me tengo que ir repartiendo entre programar y generar la documentación, por lo que no te puedo dar una fecha estimada para cuando estaría disponible una documentación más completa. Por ahora lo único relativo a armar una simulación básica es el "Getting Started".

De manera general, los parámetros disponibles en todos los componentes de Caneda son los asociados a los modelos de spice genérico. Es por esto, que su comportamiento sigue de cerca a los parámetros indicados en el ngspice-manual que vos mismo mencionás (copio el link en [2] para futura referencia de cualquiera que lea este bug). Lo mismo sucede con todas las simulaciones disponibles (que si observás en el "Components Browser" son unas cuantas). La única observación que tengo para hacer al respecto es que si bien todas se simulan correctamente, la visualización de cada tipo de simulación es un trabajo en proceso. Actualmente se visualizan correctamente las simulaciones temporales y de frecuencia ("Transient Simulation" y "AC Simulation"), el resto de las visualizaciones es justamente la tarea en la que estoy trabajando en este momento y que estará disponible para el próximo release o el siguiente a más tardar.

Por otra parte, no sé si seguís utilizando la versión 0.2.0 o actualizaste a la 0.3.0, de la cual hice el release hace unos días. Entre otras cosas, tiene la ventaja que si te olvidás de poner una tierra, un perfil de simulación, etc, te avisa y te "ayuda" a simular.

Si tenés una o más dudas puntuales sobre las simulaciones (o cualquier otra cosa), no tengo drama en ir aclarándolas de a una. Adicionalmente, si la duda se plantea de manera que la pueda plasmar en una página de la documentación, las iré agregando a los docs para que queden de manera más general.

Espero haber servido de ayuda, cualquier cosa, no dudes en escribir.

Saludos,
Pablo

## 

[1] http://docs.caneda.org/
[2] http://ngspice.sourceforge.net/docs/ngspice-manual.pdf
